layout_spectrum: 0.4785177
color:
  saturation: 0.3464017
  lightness: 0.697637
  brandStrength: 0.9070892
  brandColors:
    - '#794916'
    - '#F2BD6E'
  rhythmicContrast: 0.8104189
typography_spectrum: 0.7610097
name: hamamelidaceae
